modLoader = "javafml"
loaderVersion = "[32,)"
license = "CC0"

[[mods]]
modId = "forgeutils"
version = "${version}"
displayName = "ForgeUtils"
displayURL = "https://github.com/ThinkingStudios/ForgeUtils"
authors="TexTrue" #optional
description = '''
forge platform utils
'''

[[dependencies.forgeutils]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.forgeutils]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"
